### ISSUE TITLE
Globe.dev link is not proper.

### ISSUE THREAD

**Issue by shivams1110** [invertase/.github#4]
<img width="775" alt="Screenshot 2024-02-12 at 11 43 23 AM" src="https://github.com/invertase/.github/assets/17330509/f9b7df96-a1ce-40e5-b066-702a316fe5c5">

Here Globe.dev is opening **https://globe/dev**

Please update this to **https://globe.dev**

**Comment by Ehesp** [comment]
Thanks for reporting! Fixed
